// src/csound/CsoundGenerator.js

export class CsoundGenerator {
    constructor() {
        // Множество инклудов (typeId)
        this.includes = new Set();
        
        // Активные модули с их данными
        this.modules = new Map(); // key: instanceId, value: moduleData
        
        // Шаблон Csound
        this.template = `; generated by Nord Modular GUI

<CsoundSynthesizer>
<CsOptions>
-odac -m128
</CsOptions>
<CsInstruments>
sr = 48000
ksmps = 16
nchnls = 2
0dbfs = 1.0

gkBPM init 120 ; GLOBAL TEMPO
gaFX1 init 0 ; do we really need 3&4 fx bus?
gaFX2 init 0
gaFX3 init 0
gaFX4 init 0
;gaBU1 init 0 ; do we really need 3&4 bus?
;gaBU2 init 0

opcode K2Y, k, k  ; THIS IS TEMPORARY!
    kin xin
    kout = (kin > 0 ? 1 : 0)
    xout kout
endop

opcode A2O, a, a  ; THIS IS TEMPORARY!
    setksmps 1
    ain xin
    kin = k(ain)
    kout = (kin > 0 ? 1 : 0)
    xout a(kout)
endop

;---------------------------------
; Zak space initialization
gkNote init 64
gkGate init 0
zakinit 9, 6
massign 1,0
massign 2,0
massign 3,0
massign 4,0

;---------------------------------

;---------------------------------
; Waveforms
giSin ftgen 1, 0, 16384, 10, 1
giCos ftgen 11, 0, 16384, 11, 1, 1
giTri ftgen 2, 0, 16384, 7, 0, 4096, 1, 8192, -1, 4096, 0
;giTriP ftgen 2, 0, 16384, 7, 0, 8192, 1, 8192, 0
giTriF ftgen 24, 0, 16384, 7, -1, 8192, 1, 8192, -1
giSaw ftgen 3, 0, 16384, 7, 1, 16384, -1
giSqr50 ftgen 4, 0, 16384, 7, 1, 8192, 1, 0, -1, 8192, -1
giSqr25 ftgen 5, 0, 16384, 7, 1, 4096, 1, 0, -0.25, 12288, -0.25
giSqr10 ftgen 6, 0, 16384, 7, 1, 1024, 1, 0, -0.0625, 15360, -0.0625
giSq400 ftgen 21, 0, 16384, 7,1,41,1,0,0,16343,0 ; Sync_Wave Table CLKGEN
giSq96 ftgen 22, 0, 16384, 7,1,1366,1,0,0,15018,0 ; 1/96_Wave Table CLKGEN
giSq16 ftgen 23, 0, 16384, 7,1,910,1,0,0,15474,0 ; 1/16_Wave Table CLKGEN

;---------------------------------
; UDO section
; >>> INCLUDES WILL BE HERE <<<

; --------------------
; VOICE AREA
instr 1
; Module    Name            Parameters    Modes    Inlets    Outlets
; >>> VOICE MODULES WILL BE HERE <<<
endin

; --------------------
; FX AREA
instr 2
; Module    Name    Parameters    Modes    Inlets    Outlets
; >>> FX MODULES WILL BE HERE <<<
endin

; GLOBAL MIDI
gkstat init 0
gkchan init 0
gkdata1 init 0
gkdata2 init 0
instr 3
  gkstat, gkchan, gkdata1, gkdata2 midiin
  if gkstat != 144 goto Next
    gkGate = 1
    gkNote = gkdata1
  Next:
  if gkstat!=128 goto Over
    gkGate = 0
  Over:
endin

; FOR OFFLINE RENDERING
instr 4
  xtratim 0.1
  gkGate linsegr 1, p3, 1, 0, 0
  gkNote = p4 ; in 7b MIDI format
endin

</CsInstruments>
<CsScore>
i1 0 [60*60*24*7]
i2 0 [60*60*24*7]
i3 0 [60*60*24*7]
; use i4 to emultate MIDI commands if needed
; p4 is pitch
;i4 0 1 64
</CsScore>
</CsoundSynthesizer>`;
        
        this.log('📁 CsoundGenerator initialized');
    }
    
    addModule(moduleData) {
        console.log('🎯 addModule called with:', moduleData);
        
        const { 
            typeId,           
            instanceId,       
            instanceName,     
            layer,            
            parameters = [],  
            mode = [],         // 👈 ИСПРАВЛЕНО
            defaultParams = [],
            defaultMode = [],  // 👈 ИСПРАВЛЕНО
            inlets = 1,       
            outlets = 1       
        } = moduleData;
        
        console.log('  📦 typeId:', typeId);
        console.log('  📦 instanceId:', instanceId);
        console.log('  📦 instanceName:', instanceName);
        console.log('  📦 defaultParams:', defaultParams);
        console.log('  📦 defaultMode:', defaultMode);    // 👈 ИСПРАВЛЕНО
        console.log('  📦 inlets:', inlets);
        console.log('  📦 outlets:', outlets);
        
        // Добавляем инклуд
        const filename = `${typeId}.txt`;
        if (!this.includes.has(filename)) {
            this.includes.add(filename);
            this.log(`📄 Added include: ${filename}`);
        }
        
        // Сохраняем модуль
        const moduleKey = `${instanceName}_${instanceId}`;
        this.modules.set(moduleKey, {
            typeId,
            instanceId,
            instanceName,
            layer,
            parameters,
            mode,              // 👈 ИСПРАВЛЕНО
            defaultParams,
            defaultMode,       // 👈 ИСПРАВЛЕНО
            inlets,
            outlets
        });
        
        console.log('  ✅ Module saved with defaultParams:', defaultParams);
        console.log('  ✅ Module saved with defaultMode:', defaultMode);  // 👈 ИСПРАВЛЕНО
        
        this.log(`✅ Added module: ${moduleKey} (${layer})`);
        this.showFullCsd();
    }
    
    /**
     * Удалить модуль
     */
    removeModule(instanceId, instanceName, typeId, layer) {
        const moduleKey = `${instanceName}_${instanceId}`;
        
        if (!this.modules.has(moduleKey)) {
            this.log(`⚠️ Module not found: ${moduleKey}`, 'dim');
            return false;
        }
        
        // Удаляем модуль
        this.modules.delete(moduleKey);
        this.log(`🗑️ Removed module: ${moduleKey}`);
        
        // Проверяем, остались ли ещё модули этого типа
        const typeStillUsed = Array.from(this.modules.values())
            .some(m => m.typeId === typeId);
        
        if (!typeStillUsed) {
            // Удаляем инклуд
            const filename = `${typeId}.txt`;
            this.includes.delete(filename);
            this.log(`📄 Removed include: ${filename} (no more modules of type ${typeId})`);
        }
        
        this.showFullCsd();
        return true;
    }
    
    /**
     * Сгенерировать полный .csd
     */
    generateFullCsd() {
        // 1. Формируем инклуды
        const includesList = Array.from(this.includes).sort();
        let includeString = includesList.length === 0 
            ? '; no modules loaded'
            : includesList.map(f => `#include "${f}"`).join('\n');
        
        // 2. Формируем модули для Voice (instr 1)
        const voiceModules = Array.from(this.modules.values())
            .filter(m => m.layer === 'voice')
            .map(m => this.formatModuleLine(m))
            .join('\n');
        
        // 3. Формируем модули для FX (instr 2)
        const fxModules = Array.from(this.modules.values())
            .filter(m => m.layer === 'fx')
            .map(m => this.formatModuleLine(m))
            .join('\n');
        
        // 4. Вставляем в шаблон
        return this.template
            .replace('; >>> INCLUDES WILL BE HERE <<<', includeString)
            .replace('; >>> VOICE MODULES WILL BE HERE <<<', voiceModules || '; no voice modules')
            .replace('; >>> FX MODULES WILL BE HERE <<<', fxModules || '; no fx modules');
    }
    
    /**
     * Форматировать строку модуля
     */
    // src/csound/CsoundGenerator.js

    formatModuleLine(module) {
        console.log('🎯 formatModuleLine called with:', module);
        
        const {
            instanceName,
            instanceId,
            parameters = [],
            mode = [],           // 👈 ИСПРАВЛЕНО: mode, не modes
            defaultParams = [],
            defaultMode = [],    // 👈 ИСПРАВЛЕНО: defaultMode, не defaultModes
            inlets,
            outlets
        } = module;
        
        console.log('  📦 instanceName:', instanceName);
        console.log('  📦 instanceId:', instanceId);
        console.log('  📦 parameters:', parameters);
        console.log('  📦 mode:', mode);                    // 👈 ИСПРАВЛЕНО
        console.log('  📦 defaultParams:', defaultParams);
        console.log('  📦 defaultMode:', defaultMode);      // 👈 ИСПРАВЛЕНО
        console.log('  📦 inlets:', inlets);
        console.log('  📦 outlets:', outlets);
        
        // Очищаем имя модуля от номера версии
        const cleanModuleName = instanceName.replace(/_\d+$/, '');
        
        // Используем реальные параметры, если есть, иначе дефолтные
        const paramsToUse = parameters.length > 0 ? parameters : defaultParams;
        console.log('  📊 paramsToUse:', paramsToUse);
        
        // Используем реальные моды, если есть, иначе дефолтные
        const modeToUse = mode.length > 0 ? mode : defaultMode;  // 👈 ИСПРАВЛЕНО
        console.log('  📊 modeToUse:', modeToUse);
        
        // Параметры
        let paramsStr = '0';
        if (paramsToUse.length > 0) {
            paramsStr = paramsToUse.join(', ');
        }
        
        // Моды (часто пустые)
        let modeStr = '';
        if (modeToUse.length > 0) {
            modeStr = ', ' + modeToUse.join(', ');
        }
        
        // Формируем строку инлетов (-1 для каждого входа)
        const inletsStr = Array(inlets).fill('-1').join(', ');
        
        // Формируем строку аутлетов (-2 для каждого выхода)
        const outletsStr = Array(outlets).fill('-2').join(', ');
        
        // Финальная строка
        const result = `${cleanModuleName}   /* ${instanceName} */     ${paramsStr}${modeStr},           ${inletsStr},      ${outletsStr}`;
        
        console.log('  ✅ result:', result);
        
        return result;
    }
    
    /**
     * Показать полный .csd в консоли
     */
    showFullCsd() {
        console.log('\n' + '='.repeat(60));
        console.log('🎵 FULL CSD FILE:');
        console.log('='.repeat(60));
        console.log(this.generateFullCsd());
        console.log('='.repeat(60) + '\n');
    }
    
    log(message, style = 'normal') {
        const styles = {
            normal: 'color: #8a8a8a',
            dim: 'color: #666; font-style: italic',
            add: 'color: #8bc34a; font-weight: bold',
            remove: 'color: #ff6b6b; font-weight: bold'
        };
        console.log(`%c[CsoundGenerator] ${message}`, styles[style] || styles.normal);
    }
    
    reset() {
        this.includes.clear();
        this.modules.clear();
        this.log('🔄 Reset');
        this.showFullCsd();
    }
}