// src/csound/CsoundGenerator.js

export class CsoundGenerator {
    constructor() {
        // Множество инклудов (typeId)
        this.includes = new Set();
        
        // Активные модули с их данными
        this.modules = new Map(); // key: instanceId, value: moduleData
        
        // Счётчики шин для zakinit
        this._audioBusCount = 2;   // по умолчанию: 0 и 1 служебные
        this._controlBusCount = 2; // по умолчанию: 0 и 1 служебные
        
        // Активные кабели (для отслеживания)
        this._activeCables = [];
        
        // НОВОЕ: маппинг кабель -> номер шины
        this._cableBusMap = {};      // cableId -> busNumber
        this._audioBusCounter = 2;   // следующий свободный номер для audio
        this._controlBusCounter = 2; // следующий свободный номер для control
        this._availableAudioBuses = [];   // освободившиеся audio номера
        this._availableControlBuses = []; // освободившиеся control номера
        // Шаблон Csound (будет обновляться динамически)
        this.userModules = {};        
        this.includes.add('led_rms.txt');
        this._userModulesLoaded = false;
        this.template = `; generated by Nord Modular GUI

<CsoundSynthesizer>
<CsOptions>
-odac ;-d
</CsOptions>
<CsInstruments>
sr = 48000
ksmps = 16
nchnls = 2
0dbfs = 1.0

gkBPM init 120 ; GLOBAL TEMPO
gaFX1 init 0 ; do we really need 3&4 fx bus?
gaFX2 init 0
gaFX3 init 0
gaFX4 init 0
;gaBU1 init 0 ; do we really need 3&4 bus?
;gaBU2 init 0

opcode K2Y, k, k  ; THIS IS TEMPORARY!
    kin xin
    kout = (kin > 0 ? 1 : 0)
    xout kout
endop

opcode A2O, a, a  ; THIS IS TEMPORARY!
    setksmps 1
    ain xin
    kin = k(ain)
    kout = (kin > 0 ? 1 : 0)
    xout a(kout)
endop

;---------------------------------
; Zak space initialization
gkNote init 64
gkGate init 0
; >>> ZAKINIT WILL BE HERE <<<
massign 1,0
massign 2,0
massign 3,0
massign 4,0

;---------------------------------

;---------------------------------
; Waveforms
giSin ftgen 1, 0, 16384, 10, 1
giCos ftgen 11, 0, 16384, 11, 1, 1
giTri ftgen 2, 0, 16384, 7, 0, 4096, 1, 8192, -1, 4096, 0
;giTriP ftgen 2, 0, 16384, 7, 0, 8192, 1, 8192, 0
giTriF ftgen 24, 0, 16384, 7, -1, 8192, 1, 8192, -1
giSaw ftgen 3, 0, 16384, 7, 1, 16384, -1
giSqr50 ftgen 4, 0, 16384, 7, 1, 8192, 1, 0, -1, 8192, -1
giSqr25 ftgen 5, 0, 16384, 7, 1, 4096, 1, 0, -0.25, 12288, -0.25
giSqr10 ftgen 6, 0, 16384, 7, 1, 1024, 1, 0, -0.0625, 15360, -0.0625
giSq400 ftgen 21, 0, 16384, 7,1,41,1,0,0,16343,0 ; Sync_Wave Table CLKGEN
giSq96 ftgen 22, 0, 16384, 7,1,1366,1,0,0,15018,0 ; 1/96_Wave Table CLKGEN
giSq16 ftgen 23, 0, 16384, 7,1,910,1,0,0,15474,0 ; 1/16_Wave Table CLKGEN

;---------------------------------
; UDO section
; >>> INCLUDES WILL BE HERE <<<


; --------------------
; VOICE AREA
instr 1
; Module    Name            Parameters    Modes    Inlets    Outlets
; >>> VOICE MODULES WILL BE HERE <<<
endin

; --------------------
; FX AREA
instr 2
; Module    Name    Parameters    Modes    Inlets    Outlets
; >>> FX MODULES WILL BE HERE <<<
endin

; GLOBAL MIDI
gkstat init 0
gkchan init 0
gkdata1 init 0
gkdata2 init 0
instr 3
  gkstat, gkchan, gkdata1, gkdata2 midiin
  if gkstat != 144 goto Next
    gkGate = 1
    gkNote = gkdata1
  Next:
  if gkstat!=128 goto Over
    gkGate = 0
  Over:
endin

; FOR OFFLINE RENDERING
instr 4
  xtratim 0.1
  gkGate linsegr 1, p3, 1, 0, 0
  gkNote = p4 ; in 7b MIDI format
endin

</CsInstruments>
<CsScore>
i1 0 [60*60*24*7]
i2 0 [60*60*24*7]
i3 0 [60*60*24*7]
; use i4 to emultate MIDI commands if needed
; p4 is pitch
;i4 0 1 64
</CsScore>
</CsoundSynthesizer>`;
        
        this.log('📁 CsoundGenerator initialized');
    }


// src/csound/CsoundGenerator.js
/**
     * Загрузить содержимое UDO файла по typeID
     */
    async loadUdoContent(typeId) {
        try {
            const response = await fetch(`/csound/modules/${typeId}.txt`);
            if (!response.ok) {
                console.warn(`⚠️ UDO file not found: ${typeId}.txt`);
                return null;
            }
            const content = await response.text();
            return content;
        } catch (error) {
            console.warn(`⚠️ Failed to load UDO: ${typeId}.txt`, error);
            return null;
        }
    }

    /**
     * Загрузить все UDO содержимое для активных модулей
     */
    async loadAllUdoContents() {
        const udoContents = [];
        
        for (const filename of this.includes) {
            // filename = "4.txt", "31.txt" и т.д.
            const typeId = filename.replace('.txt', '');
            const content = await this.loadUdoContent(typeId);
            if (content) {
                udoContents.push(content);
            }
        }
        
        return udoContents;
    }

// src/csound/CsoundGenerator.js - полный generateOrc()

    async generateOrc() {
        // ⭐ 1. Загружаем все UDO содержимое для встроенных модулей
        const udoContents = [];
        const includesList = Array.from(this.includes).sort();
        
        for (const filename of includesList) {
            try {
                const response = await fetch(`/csound/modules/${filename}`);
                if (response.ok) {
                    const content = await response.text();
                    udoContents.push(content);
                    console.log(`✅ Loaded UDO: ${filename}`);
                } else {
                    console.warn(`⚠️ UDO file not found: ${filename}`);
                    udoContents.push(`; UDO ${filename} not found\nopcode ${filename.replace('.txt', '')}, 0, 0\n; empty\nendop`);
                }
            } catch (error) {
                console.warn(`⚠️ Failed to load UDO: ${filename}`, error);
                udoContents.push(`; UDO ${filename} not found (error)\nopcode ${filename.replace('.txt', '')}, 0, 0\n; empty\nendop`);
            }
        }
        
        const udoString = udoContents.join('\n\n');
        
        // ⭐ 2. Собираем модули из патча (voice и fx)
        const voiceModules = Array.from(this.modules.values())
            .filter(m => m.layer === 'voice')
            .map(m => this.formatModuleLine(m))
            .join('\n');
        
        const fxModules = Array.from(this.modules.values())
            .filter(m => m.layer === 'fx')
            .map(m => this.formatModuleLine(m))
            .join('\n');
        
        // ⭐ 3. Zakinit
        const zakinitString = this.getZakInitString();
        

        // ⭐ 4. ПОЛЬЗОВАТЕЛЬСКИЕ МОДУЛИ
        // Управляются через this.includes (user/*.txt), а не через this.userModules.
        // this.userModules остаётся как реестр метаданных, но НЕ вставляется в ORC.
        const userModulesCode = '';
        
        // ⭐ 5. Формируем полный ORC
        return `
    sr = 48000
    ksmps = 4
    nchnls = 2
    0dbfs = 1.0

    gkBPM init 120
    gaFX1 init 0
    gaFX2 init 0
    gaFX3 init 0
    gaFX4 init 0

    opcode K2Y, k, k
        kin xin
        kout = (kin > 0 ? 1 : 0)
        xout kout
    endop

    opcode A2O, a, a
        ; setksmps 1  ; ⭐ закомментировано для стабильности
        ain xin
        kin = k(ain)
        kout = (kin > 0 ? 1 : 0)
        xout a(kout)
    endop

    gkNote init 64
    gkGate init 0
    ${zakinitString}
    massign 1,0
    massign 2,0
    massign 3,0
    massign 4,0

    giSin ftgen 1, 0, 16384, 10, 1
    giCos ftgen 11, 0, 16384, 11, 1, 1
    giTri ftgen 2, 0, 16384, 7, 0, 4096, 1, 8192, -1, 4096, 0
    giTriF ftgen 24, 0, 16384, 7, -1, 8192, 1, 8192, -1
    giSaw ftgen 3, 0, 16384, 7, 1, 16384, -1
    giSqr50 ftgen 4, 0, 16384, 7, 1, 8192, 1, 0, -1, 8192, -1
    giSqr25 ftgen 5, 0, 16384, 7, 1, 4096, 1, 0, -0.25, 12288, -0.25
    giSqr10 ftgen 6, 0, 16384, 7, 1, 1024, 1, 0, -0.0625, 15360, -0.0625
    giSq400 ftgen 21, 0, 16384, 7,1,41,1,0,0,16343,0
    giSq96 ftgen 22, 0, 16384, 7,1,1366,1,0,0,15018,0
    giSq16 ftgen 23, 0, 16384, 7,1,910,1,0,0,15474,0

    ;---------------------------------
    ; UDO section (inlined from /csound/modules/*.txt)
    ${udoString}

    ;---------------------------------
    ; VOICE AREA
    instr 1
    ${voiceModules || '; no voice modules'}
    endin

    ;---------------------------------
    ; FX AREA
    instr 2
    ${fxModules || '; no fx modules'}
    endin

    ;---------------------------------
    ; GLOBAL MIDI
    gkstat init 0
    gkchan init 0
    gkdata1 init 0
    gkdata2 init 0
    instr 3
      gkstat, gkchan, gkdata1, gkdata2 midiin
      if gkstat != 144 goto Next
        gkGate = 1
        gkNote = gkdata1
      Next:
      if gkstat!=128 goto Over
        gkGate = 0
      Over:
    endin

    ;---------------------------------
    ; FOR OFFLINE RENDERING
    instr 4
      xtratim 0.1
      gkGate linsegr 1, p3, 1, 0, 0
      gkNote = p4
    endin
    `;
    }

    generateSco() {
        // Пока пусто — ноты будут добавляться через inputMessage
        // Но для инициализации можно оставить пустым или с тестовой нотой
        return `
    i1 0 [60*60*24*7]
    i2 0 [60*60*24*7]
    i3 0 [60*60*24*7]
    ; use i4 to emulate MIDI commands if needed
    ;i4 0 1 64
    `;
    }



    // ⭐⭐⭐ НОВЫЕ МЕТОДЫ ДЛЯ РАБОТЫ С КАБЕЛЯМИ ⭐⭐⭐
    
    /**
     * Добавить кабель
     */
    addCable(cable) {
        this._activeCables.push(cable);
        // ⭐ Назначаем номер шины
        this._assignBusNumberToCable(cable);
        this._updateZakInit();
        this.log(`🔌 Added cable, zakinit updated`);
    }
    
    /**
     * Назначить номер шины кабелю
     */
    _assignBusNumberToCable(cable) {
        if (this._cableBusMap[cable.id] !== undefined) {
            return;
        }
        
        // Проверяем, есть ли уже кабель с таким же выходом
        const outputJack = cable.fromJack;
        if (outputJack) {
            const existingCable = this._activeCables.find(c => 
                c.fromJack === outputJack && 
                c.id !== cable.id &&
                this._cableBusMap[c.id] !== undefined
            );
            if (existingCable) {
                const busNumber = this._cableBusMap[existingCable.id];
                this._cableBusMap[cable.id] = busNumber;
                this.log(`🔢 Cable ${cable.id.substr(0, 8)} → bus ${busNumber} (shared from same output)`);
                return;
            }
        }
        
        const cableType = this._getCableType(cable);
        let busNumber;
        
        if (cableType === 'audio') {
            // ⭐ Сначала проверяем освободившиеся номера
            if (this._availableAudioBuses.length > 0) {
                this._availableAudioBuses.sort((a, b) => a - b);
                busNumber = this._availableAudioBuses.shift();
            } else {
                busNumber = this._audioBusCounter++;
            }
        } else {
            if (this._availableControlBuses.length > 0) {
                this._availableControlBuses.sort((a, b) => a - b);
                busNumber = this._availableControlBuses.shift();
            } else {
                busNumber = this._controlBusCounter++;
            }
        }
        
        this._cableBusMap[cable.id] = busNumber;
        this.log(`🔢 Cable ${cable.id.substr(0, 8)} → bus ${busNumber} (${cableType})`);
    }


    getBusNumberForCable(cable) {
        return this._cableBusMap[cable.id];
    }
    
    removeCable(cable) {
        const index = this._activeCables.indexOf(cable);
        if (index > -1) {
            this._activeCables.splice(index, 1);
            
            // ⭐ Освобождаем номер шины для переиспользования
            if (this._cableBusMap[cable.id] !== undefined) {
                const busNumber = this._cableBusMap[cable.id];
                const cableType = this._getCableType(cable);
                
                // Проверяем, не использует ли этот номер другой кабель (от того же выхода)
                const isShared = this._activeCables.some(c => 
                    c.id !== cable.id && 
                    this._cableBusMap[c.id] === busNumber
                );
                
                if (!isShared) {
                    // Номер больше не используется → добавляем в доступные
                    if (cableType === 'audio') {
                        this._availableAudioBuses.push(busNumber);
                    } else {
                        this._availableControlBuses.push(busNumber);
                    }
                    this.log(`🔢 Bus ${busNumber} freed (${cableType})`);
                }
                
                delete this._cableBusMap[cable.id];
            }
            
            this._updateZakInit();
            this.log(`🔌 Removed cable, zakinit updated`);
        }
    }
    
    /**
     * Очистить все кабели
     */
    clearCables() {
        this._activeCables = [];
        this._cableBusMap = {};
        this._audioBusCounter = 2;
        this._controlBusCounter = 2;
        this._updateZakInit();
        this.log(`🔌 All cables cleared, zakinit reset`);
    }
    
    /**
     * Обновить zakinit на основе кабелей
     */
    _updateZakInit() {
        let audioCount = 0;
        let controlCount = 0;
        
        for (const cable of this._activeCables) {
            const cableType = this._getCableType(cable);
            if (cableType === 'audio') {
                audioCount++;
            } else if (cableType === 'control') {
                controlCount++;
            }
        }
        
        this._audioBusCount = 2 + audioCount;
        this._controlBusCount = 2 + controlCount;
        
        console.log(`🎛️ zakinit: audio=${this._audioBusCount} (2 + ${audioCount}), control=${this._controlBusCount} (2 + ${controlCount})`);
    }
    
    /**
     * Определяем тип кабеля по цвету
     */
    _getCableType(cable) {
        const color = cable.getDisplayColor ? cable.getDisplayColor() : cable.color;
        console.log(`🔍 Getting cable type for color: ${color}`);
        
        // Audio цвета
        const audioColors = ['#ef4444', '#ff0000', '#ff4444', '#ff6b6b', '#ff8800', '#ffa500', '#ff8c00'];
        // Control цвета
        const controlColors = ['#3b82f6', '#0000ff', '#4488ff', '#fde047', '#ffff00', '#ffd93d', '#ffdd57'];
        
        if (!color) {
            console.log('  No color, defaulting to audio');
            return 'audio';
        }
        
        const colorLower = color.toLowerCase();
        
        for (const audioColor of audioColors) {
            if (colorLower === audioColor.toLowerCase()) {
                console.log(`  ✅ Color ${color} is AUDIO`);
                return 'audio';
            }
        }
        
        for (const controlColor of controlColors) {
            if (colorLower === controlColor.toLowerCase()) {
                console.log(`  ✅ Color ${color} is CONTROL`);
                return 'control';
            }
        }
        
        console.log(`  ⚠️ Color ${color} not recognized, defaulting to audio`);
        return 'audio';
    }
    
    /**
     * Получить строку zakinit
     */
    getZakInitString() {
        return `zakinit ${this._audioBusCount}, ${this._controlBusCount}`;
    }

/**
 * Найти кабель, подключенный к порту (входу)
 */
    _findCableForPort(moduleId, componentId, direction) {
        const targetId = parseInt(componentId);
        
        for (const cable of this._activeCables) {
            const jack = direction === 'input' ? cable.toJack : cable.fromJack;
            if (!jack) continue;
            
            let parentId = jack.parentModule?.jsonId || jack.parentModule?.moduleId;
            if (!parentId && jack.module) {
                parentId = jack.module.jsonId || jack.module.moduleId;
            }
            if (!parentId && jack.parent) {
                parentId = jack.parent.jsonId || jack.parent.moduleId;
            }
            
            if (parentId !== moduleId) continue;
            
            // ⭐ Сравниваем по ID компонента
            if (parseInt(jack.id) === targetId) {
                return cable;
            }
        }
        return null;
    }


    addModule(moduleData) {
        console.log('🎯 addModule called with:', moduleData);
        
        const { 
            typeId,           // ← это может быть строка ("Noise") или число (31)
            instanceId,       
            instanceName,     
            layer,            
            parameters = [],  
            mode = [],        
            defaultParams = [],
            defaultMode = [], 
            inlets = 1,       
            outlets = 1,   
            isUser = false  
        } = moduleData;
        
        // ⭐ Получаем числовой typeID из определения модуля
        const moduleDef = this.system?.moduleFactory?.moduleRegistry?.[typeId];
        let numericTypeId = typeId;
        
        // Если есть определение, берём typeID из него
        if (moduleDef && moduleDef.typeID !== undefined) {
            numericTypeId = moduleDef.typeID;
            console.log(`  🔢 Found typeID in definition: ${numericTypeId}`);
        } else {
            // Пробуем найти typeID в модулях по имени
            const registry = this.system?.moduleFactory?.moduleRegistry;
            if (registry) {
                for (const [key, def] of Object.entries(registry)) {
                    if (key === typeId && def.typeID !== undefined) {
                        numericTypeId = def.typeID;
                        console.log(`  🔢 Found typeID by key match: ${numericTypeId}`);
                        break;
                    }
                }
            }
        }
        
        // ⭐ Определяем путь к UDO-файлу
        let filename;
        if (isUser) {
            // Пользовательский: /csound/modules/user/Zgen.txt
            filename = `user/${typeId}.txt`;
        } else {
            // Встроенный: /csound/modules/9.txt
            filename = `${numericTypeId}.txt`;
        }

        if (!this.includes.has(filename)) {
            this.includes.add(filename);
            this.log(`📄 Added include: ${filename}`);
        }
        // Сохраняем модуль с правильным typeId
        const moduleKey = `${instanceName}_${instanceId}`;
        this.modules.set(moduleKey, {
            typeId: typeId,           // "Noise" для поиска в registry
            numericTypeId: numericTypeId, // 31 для include
            instanceId,
            instanceName,
            layer,
            parameters,
            mode,
            defaultParams,
            defaultMode,
            inlets,
            outlets,
            isUser,
            udoPath: filename,
        });
        
        console.log('  ✅ Module saved with numericTypeId:', numericTypeId);
        this.log(`✅ Added module: ${moduleKey} (${layer})`);
        //this.showFullCsd();
    }
    
    removeModule(instanceId, instanceName, typeId, layer) {
        const moduleKey = `${instanceName}_${instanceId}`;
        
        if (!this.modules.has(moduleKey)) {
            this.log(`⚠️ Module not found: ${moduleKey}`, 'dim');
            return false;
        }
        
        // ⭐ Получаем udoPath ДО удаления
        const removedModule = this.modules.get(moduleKey);
        const udoPath = removedModule?.udoPath;
        
        this.modules.delete(moduleKey);
        this.log(`🗑️ Removed module: ${moduleKey}`);
        
        // ⭐ Проверяем, используется ли ещё этот UDO
        const pathStillUsed = Array.from(this.modules.values())
            .some(m => m.udoPath === udoPath);
        
        if (!pathStillUsed && udoPath) {
            this.includes.delete(udoPath);
            this.log(`📄 Removed include: ${udoPath}`);
        }
        
        return true;
    }
    
/**
 * Сгенерировать полный CSD (для экспорта в файл) - НОВАЯ ВЕРСИЯ
 */
    async generateFullCsd() {
        const orc = await this.generateOrc();
        return `<CsoundSynthesizer>
    <CsOptions>
    -odac ;-d
    </CsOptions>
    <CsInstruments>
    ${orc}
    </CsInstruments>
    <CsScore>
    i1 0 [60*60*24*7]
    i2 0 [60*60*24*7]
    i3 0 [60*60*24*7]
    </CsScore>
    </CsoundSynthesizer>`;
    }
    
    formatModuleLine(module) {
        console.log('🎯 formatModuleLine called with:', module);
        
        const {
            instanceName,
            instanceId,
            parameters = [],
            mode = [],
            defaultParams = [],
            defaultMode = [],
            inlets,
            outlets,
            typeId,
            numericTypeId
        } = module;
        
        const panel = this.getPanelById(instanceId);
        const moduleDef = this.system?.moduleFactory?.moduleRegistry?.[typeId];
        
        // ⭐ Имя модуля (opcode)
        let moduleName = typeId;
        if (moduleDef && moduleDef.type) {
            moduleName = moduleDef.type;
        }
        
        console.log(`  📛 Module name: ${moduleName} (typeID: ${numericTypeId})`);
        
        // ⭐ ID входов/выходов из определения модуля
        const inputIds = moduleDef?.inputs || [];
        const outputIds = moduleDef?.outputs || [];
        
        console.log(`  📊 Input IDs:`, inputIds);
        console.log(`  📊 Output IDs:`, outputIds);
        
        // ⭐ Для каждого ID входа — ищем кабель
        const inletBuses = inputIds.map(id => {
            const cable = this._findCableForPort(instanceId, id, 'input');
            if (cable && this._cableBusMap[cable.id] !== undefined) {
                console.log(`  🔗 Input id=${id} → bus ${this._cableBusMap[cable.id]}`);
                return this._cableBusMap[cable.id];
            }
            console.log(`  🔗 Input id=${id} → 1 (empty)`);
            return 1;
        });
        
        // ⭐ Для каждого ID выхода — ищем кабели
        const outletBuses = outputIds.map(id => {
            const cables = this._findCablesForOutput(instanceId, id);
            if (cables.length > 0) {
                const busNumber = this._cableBusMap[cables[0].id];
                if (busNumber !== undefined) {
                    console.log(`  🔗 Output id=${id} → bus ${busNumber} (${cables.length} cables)`);
                    return busNumber;
                }
            }
            console.log(`  🔗 Output id=${id} → 0 (ground)`);
            return 0;
        });
        
        console.log(`  📊 Inlet buses:`, inletBuses);
        console.log(`  📊 Outlet buses:`, outletBuses);
        
        // ⭐ Параметры из moduleDef.params (в порядке opcode)
        const paramIds = moduleDef?.params || [];
        const chngetLines = [];
        const paramArgs = [];
        
        if (paramIds.length > 0) {
            // User-модуль с явными params — генерируем chnget
            paramIds.forEach(compId => {
                const comp = panel?.components.find(c => String(c.id) === String(compId));
                
                if (!comp) {
                    console.warn(`  ⚠️ Param id=${compId} not found in panel`);
                    paramArgs.push('0');
                    return;
                }
                
                const channelName = `module_${instanceName}_${instanceId}_${compId}`;
                const varName = `k_${instanceName}_${instanceId}_${compId}`;
                
                chngetLines.push(`${varName} chnget "${channelName}"`);
                paramArgs.push(varName);
            });
        } else {
            // Fallback: NM2-модули — используем defaultParams как значения
            const paramsToUse = parameters.length > 0 ? parameters : defaultParams;
            paramsToUse.forEach(p => paramArgs.push(String(p)));
        }
        
        // ⭐ Mode (пока без изменений)
        const modeArgs = [];
        const modeToUse = mode.length > 0 ? mode : defaultMode;
        if (modeToUse.length > 0) {
            modeToUse.forEach(m => modeArgs.push(String(m)));
        }
        
        // ⭐ Все аргументы по порядку
        const allArgs = [
            ...paramArgs,
            ...modeArgs,
            ...inletBuses.map(String),
            ...outletBuses.map(String),
        ];
        
        const callLine = `${moduleName} ${allArgs.join(', ')}`;

        // ⭐ ⭐ ⭐ LED-строки (для каждой лампочки в модуле)
        const ledLines = [];
        if (panel && moduleDef?.components) {
            const leds = panel.components.filter(c => c.constructor.name === 'LED');
            
            leds.forEach(led => {
                // ⭐ Ищем source-компонент (Input или Output)
                if (led.sourceComponentId === null || led.sourceComponentId === undefined) {
                    console.log(`  ⚠️ LED id=${led.id} has no sourceComponentId`);
                    return;
                }
                
                const sourceComp = panel.components.find(c => 
                    String(c.id) === String(led.sourceComponentId)
                );
                
                if (!sourceComp) {
                    console.log(`  ⚠️ LED id=${led.id}: source id=${led.sourceComponentId} not found`);
                    return;
                }
                
                const sourceType = sourceComp.constructor.name;
                let bus = null;
                
                if (sourceType === 'Input') {
                    // LED на входе — читаем то, что приходит в Input
                    const inputIndex = inputIds.indexOf(parseInt(sourceComp.id));
                    if (inputIndex === -1) {
                        console.log(`  ⚠️ LED id=${led.id}: input id=${sourceComp.id} not in moduleDef.inputs`);
                        return;
                    }
                    bus = inletBuses[inputIndex];
                } else if (sourceType === 'Output') {
                    // LED на выходе — читаем то, что выходит из Output
                    const outputIndex = outputIds.indexOf(parseInt(sourceComp.id));
                    if (outputIndex === -1) {
                        console.log(`  ⚠️ LED id=${led.id}: output id=${sourceComp.id} not in moduleDef.outputs`);
                        return;
                    }
                    bus = outletBuses[outputIndex];
                } else {
                    console.log(`  ⚠️ LED id=${led.id}: source type ${sourceType} not supported`);
                    return;
                }
                
                if (!bus || bus === 0) {
                    // ⭐ bus 0 = ground, LED просто не горит
                    console.log(`  🔗 LED id=${led.id}: bus=0 (ground), skipping`);
                    return;
                }
                
                // ⭐ Имя канала (уникальное)
                const channelName = `led_${instanceName}_${instanceId}_${led.id}`;
                const ledType = led.ledType || 'rms';
                
                console.log(`  💡 LED id=${led.id} → ${ledType}(${bus}, "${channelName}")`);
                
                // ⭐ Строка вызова LED-UDO
                ledLines.push(`led_${ledType} ${bus}, "${channelName}"`);
            });
        }

        const result = [
            ...chngetLines,
            callLine,
            ...ledLines,
        ].join('\n');

        console.log('  ✅ result:', result);
        return result;
    }

    _findCablesForOutput(moduleId, componentId) {
        const targetId = parseInt(componentId);
        const result = [];
        
        for (const cable of this._activeCables) {
            const jack = cable.fromJack;
            if (!jack) continue;
            
            let parentId = jack.parentModule?.jsonId || jack.parentModule?.moduleId;
            if (!parentId && jack.module) {
                parentId = jack.module.jsonId || jack.module.moduleId;
            }
            if (!parentId && jack.parent) {
                parentId = jack.parent.jsonId || jack.parent.moduleId;
            }
            
            if (parentId !== moduleId) continue;
            
            if (parseInt(jack.id) === targetId) {
                result.push(cable);
            }
        }
        
        return result;
    }

    getPanelById(instanceId) {
        if (this.system) {
            return this.system.components.find(
                c => c.jsonId === instanceId && c.constructor.name === 'Panel'
            );
        }
        return null;
    }

    async showFullCsd() {
        console.log('\n' + '='.repeat(60));
        console.log('🎵 FULL CSD FILE:');
        console.log('='.repeat(60));
        const csd = await this.generateFullCsd();
        console.log(csd);
        console.log('='.repeat(60) + '\n');
    }


    // В CsoundGenerator
    getLedChannelName(instanceName, instanceId, ledId) {
        return `led_${instanceName}_${instanceId}_${ledId}`;
    }
  
    log(message, style = 'normal') {
        const styles = {
            normal: 'color: #8a8a8a',
            dim: 'color: #666; font-style: italic',
            add: 'color: #8bc34a; font-weight: bold',
            remove: 'color: #ff6b6b; font-weight: bold'
        };
        console.log(`%c[CsoundGenerator] ${message}`, styles[style] || styles.normal);
    }
    
    reset() {
        this.includes.clear();
        this.modules.clear();
        this._activeCables = [];
        this._cableBusMap = {};
        this._audioBusCounter = 2;
        this._controlBusCounter = 2;
        this._audioBusCount = 2;
        this._controlBusCount = 2;
        this.log('🔄 Reset');
        //this.showFullCsd();
    }

    // ⭐ РЕГИСТРАЦИЯ ПОЛЬЗОВАТЕЛЬСКОГО МОДУЛЯ
    registerUserModule(name, data) {
        this.userModules[name] = data;
        console.log(`📝 CsoundGenerator: registered user module "${name}"`);
    }

    // ⭐ ЗАГРУЗКА ПОЛЬЗОВАТЕЛЬСКИХ МОДУЛЕЙ
    async loadUserModules() {
        try {
            const response = await fetch('/api/list-user-modules');
            if (!response.ok) return;
            
            const data = await response.json();
            const modules = data.modules || [];
            
            for (const name of modules) {
                const loadResponse = await fetch(`/api/load-module/${name}`);
                if (!loadResponse.ok) continue;
                
                const moduleData = await loadResponse.json();
                this.registerUserModule(name, {
                    jsCode: moduleData.code,
                    dspCode: moduleData.dsp_code,
                    displayName: this._extractDisplayName(moduleData.code) || name,
                    gridHeight: this._extractGridHeight(moduleData.code) || 3,
                    inputs: this._extractInputs(moduleData.code) || [],
                    outputs: this._extractOutputs(moduleData.code) || []
                });
            }
        } catch (error) {
            console.warn('Could not load user modules:', error);
        }
    }

    // ⭐ ВСПОМОГАТЕЛЬНЫЕ МЕТОДЫ ДЛЯ ПАРСИНГА
    _extractDisplayName(code) {
        const match = code.match(/displayName:\s*['"]([^'"]+)['"]/);
        return match ? match[1] : null;
    }

    _extractGridHeight(code) {
        const match = code.match(/gridHeight:\s*(\d+)/);
        return match ? parseInt(match[1]) : null;
    }

    _extractInputs(code) {
        const match = code.match(/inputs:\s*\[([^\]]*)\]/);
        if (!match) return null;
        return match[1].split(',').map(s => parseInt(s.trim())).filter(n => !isNaN(n));
    }

    _extractOutputs(code) {
        const match = code.match(/outputs:\s*\[([^\]]*)\]/);
        if (!match) return null;
        return match[1].split(',').map(s => parseInt(s.trim())).filter(n => !isNaN(n));
    }


}