// src/csound/IncludeLogger.js

export class IncludeLogger {
    constructor() {
        this.includes = new Set();
        
        // Шаблон Csound (можно вынести в отдельный файл потом)
        this.template = `; generated by Nord Modular GUI
; https://github.com/cybercable

<CsoundSynthesizer>
<CsOptions>
-odac -m128
</CsOptions>
<CsInstruments>
sr = 48000
ksmps = 16
nchnls = 2
0dbfs = 1.0

; >>> INCLUDES WILL BE HERE <<<

instr 1
endin

</CsInstruments>
<CsScore>
</CsScore>
</CsoundSynthesizer>`;
        
        this.log('📁 IncludeLogger initialized');
    }
    
    /**
     * Добавить модуль
     */
    addModule(typeId) {
        const filename = `${typeId}.txt`;
        
        if (this.includes.has(filename)) {
            this.log(`⏭️ Already have: ${filename}`, 'dim');
            return false;
        }
        
        this.includes.add(filename);
        this.log(`✅ Added: ${filename}`);
        this.showFullCsd();
        return true;
    }
    
    /**
     * Удалить модуль (если последний)
     */
    removeModule(typeId, activeTypeIds) {
        const count = activeTypeIds.filter(id => id === typeId).length;
        
        if (count > 0) {
            this.log(`ℹ️ Type ${typeId} still used by ${count} modules`, 'dim');
            return false;
        }
        
        const filename = `${typeId}.txt`;
        
        if (this.includes.has(filename)) {
            this.includes.delete(filename);
            this.log(`🗑️ Removed: ${filename}`);
            this.showFullCsd();
            return true;
        }
        
        return false;
    }
    
    /**
     * Показать полный .csd файл в консоли
     */
    showFullCsd() {
        const includes = Array.from(this.includes).sort();
        
        // Формируем строку с инклудами
        let includeString = '';
        if (includes.length === 0) {
            includeString = '; no modules loaded';
        } else {
            includeString = includes.map(f => `#include "${f}"`).join('\n');
        }
        
        // Вставляем в шаблон
        const fullCsd = this.template.replace(
            '; >>> INCLUDES WILL BE HERE <<<',
            includeString
        );
        
        console.log('\n' + '='.repeat(60));
        console.log('🎵 FULL CSD FILE:');
        console.log('='.repeat(60));
        console.log(fullCsd);
        console.log('='.repeat(60) + '\n');
    }
    
    /**
     * Получить полный .csd как строку
     */
    getFullCsd() {
        const includes = Array.from(this.includes).sort();
        let includeString = includes.length === 0 
            ? '; no modules loaded'
            : includes.map(f => `#include "${f}"`).join('\n');
            
        return this.template.replace(
            '; >>> INCLUDES WILL BE HERE <<<',
            includeString
        );
    }
    
    log(message, style = 'normal') {
        const styles = {
            normal: 'color: #8a8a8a',
            dim: 'color: #666; font-style: italic',
            add: 'color: #8bc34a; font-weight: bold',
            remove: 'color: #ff6b6b; font-weight: bold'
        };
        console.log(`%c[IncludeLogger] ${message}`, styles[style] || styles.normal);
    }
    
    reset() {
        this.includes.clear();
        this.log('🔄 Reset');
        this.showFullCsd();
    }
}